---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cliente
  template:
    metadata:
      labels:
        app: cliente
    spec:
      containers:
      - name: cliente
        image: angelmanchan/prueba:latest
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: cliente-service
spec:
  selector:
    app: cliente
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort

